CREATE TABLE Setup (
	STPID SMALLINT NOT NULL PRIMARY KEY, 
	STPVAL VARCHAR(64) NOT NULL)

CREATE TABLE Rules (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	NAME VARCHAR(32) UNIQUE NOT NULL, 
	DESCR VARCHAR(256) NOT NULL)

CREATE TABLE Coder1 (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	RULEID SMALLINT NOT NULL REFERENCES Rules (ID), 
	COUNT SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	NAME VARCHAR(16) UNIQUE NOT NULL, 
	DESCR VARCHAR(128) NOT NULL)

CREATE TABLE CODER2 (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	RULEID SMALLINT NOT NULL REFERENCES Rules (ID), 
	COUNT SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	NAME VARCHAR(16) UNIQUE NOT NULL, 
	DESCR VARCHAR(128) NOT NULL)

CREATE TABLE CODER3 (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	RULEID SMALLINT NOT NULL REFERENCES Rules (ID), 
	COUNT SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	NAME VARCHAR(16) UNIQUE NOT NULL, 
	DESCR VARCHAR(128) NOT NULL)

CREATE TABLE CODER4 (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	RULEID SMALLINT NOT NULL REFERENCES Rules (ID), 
	COUNT SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	NAME VARCHAR(16) UNIQUE NOT NULL, 
	DESCR VARCHAR(128) NOT NULL)

CREATE TABLE Specialties (
	SPYID SMALLINT NOT NULL PRIMARY KEY, 
	DASH CHAR(1) NOT NULL,
	WLOAD CHAR(1) NOT NULL,
	CODESPEC CHAR(1) NOT NULL,
	SPYNAME VARCHAR(16) NOT NULL)

CREATE TABLE Accessions (
	ACCID SMALLINT NOT NULL PRIMARY KEY, 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	DASH CHAR(1) NOT NULL,
	WLOAD CHAR(1) NOT NULL,
	ACCNAME VARCHAR(30) NOT NULL)

CREATE TABLE Subspecial (
	SUBID SMALLINT NOT NULL PRIMARY KEY, 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	SUBINIT VARCHAR(3) NOT NULL, 
	SUBNAME VARCHAR(30) NOT NULL)

CREATE TABLE Facilities (
	FACID SMALLINT NOT NULL PRIMARY KEY, 
	DASH CHAR(1) NOT NULL, 
	WLOAD CHAR(1) NOT NULL, 
	CODE VARCHAR(4) NOT NULL, 
	NAME VARCHAR(80) NOT NULL)

CREATE TABLE Groups (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	GRP SMALLINT NOT NULL, 
	CODE1 SMALLINT NOT NULL REFERENCES CODER1 (ID), 
	CODE2 SMALLINT NOT NULL REFERENCES CODER2 (ID), 
	CODE3 SMALLINT NOT NULL REFERENCES CODER3 (ID),  
	CODE4 SMALLINT NOT NULL REFERENCES CODER4 (ID), 
	NAME VARCHAR(8) UNIQUE NOT NULL)

CREATE TABLE Personnel (
	PERID SMALLINT NOT NULL PRIMARY KEY, 
	ACCESS INT NOT NULL, 
	CODE CHAR(2) NOT NULL, 
	INITIALS CHAR(3) NOT NULL, 
	PLAST VARCHAR(30) NOT NULL, 
	PFIRST VARCHAR(30) NOT NULL)

CREATE TABLE MasterSpecimens (
	MSID SMALLINT NOT NULL PRIMARY KEY, 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	SUBID SMALLINT NOT NULL REFERENCES Subspecial (SUBID), 
	PROCID SMALLINT NOT NULL, 
	ISLN SMALLINT NOT NULL, 
	GROSS SMALLINT NOT NULL, 
	EMBED SMALLINT NOT NULL, 
	MICROTOMY SMALLINT NOT NULL, 
	ROUTE SMALLINT NOT NULL, 
	SIGNOUT SMALLINT NOT NULL, 
	CODE1B SMALLINT NOT NULL REFERENCES CODER1 (ID), 
	CODE1M SMALLINT NOT NULL REFERENCES CODER1 (ID), 
	CODE1R SMALLINT NOT NULL REFERENCES CODER1 (ID), 
	CODE2B SMALLINT NOT NULL REFERENCES CODER2 (ID), 
	CODE2M SMALLINT NOT NULL REFERENCES CODER2 (ID), 
	CODE2R SMALLINT NOT NULL REFERENCES CODER2 (ID), 
	CODE3B SMALLINT NOT NULL REFERENCES CODER3 (ID), 
	CODE3M SMALLINT NOT NULL REFERENCES CODER3 (ID), 
	CODE3R SMALLINT NOT NULL REFERENCES CODER3 (ID), 
	CODE4B SMALLINT NOT NULL REFERENCES CODER4 (ID), 
	CODE4M SMALLINT NOT NULL REFERENCES CODER4 (ID), 
	CODE4R SMALLINT NOT NULL REFERENCES CODER4 (ID), 
	CODE VARCHAR(15) UNIQUE NOT NULL, 
	DESCR VARCHAR(80) NOT NULL)

CREATE TABLE MasterOrders (
	ID SMALLINT NOT NULL PRIMARY KEY, 
	GRPID SMALLINT NOT NULL REFERENCES Groups (ID), 
	CODE VARCHAR(15) UNIQUE NOT NULL, 
	DESCR VARCHAR(80) NOT NULL)

CREATE TABLE Cases (
	CASEID INT NOT NULL PRIMARY KEY, 
	FACID SMALLINT NOT NULL REFERENCES Facilities (FACID), 
	MSID SMALLINT NOT NULL REFERENCES MasterSpecimens (MSID), 
	GROSSID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	FINALID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	SUBID SMALLINT NOT NULL REFERENCES Subspecial (SUBID), 
	GROSSTAT SMALLINT NOT NULL, 
	ROUTETAT SMALLINT NOT NULL, 
	FINALTAT SMALLINT NOT NULL, 
	TOTALTAT SMALLINT NOT NULL, 
	PROID SMALLINT NOT NULL, 
	NOSPECS SMALLINT NOT NULL, 
	NOBLOCKS SMALLINT NOT NULL, 
	NOSLIDES SMALLINT NOT NULL, 
	NOSYNOPT SMALLINT NOT NULL, 
	NOFS SMALLINT NOT NULL, 
	ACCESSED DATE NOT NULL, 
	GROSSED DATE NOT NULL, 
	ROUTED DATE NOT NULL, 
	FINALED TIMESTAMP NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	VALUE4 DECIMAL(5,3) NOT NULL, 
	CASENO CHAR(12) UNIQUE NOT NULL)

CREATE TABLE Specimens (
	SPECID INT NOT NULL PRIMARY KEY, 
	CASEID INT NOT NULL REFERENCES Cases (CASEID), 
	MSID SMALLINT NOT NULL REFERENCES MasterSpecimens (MSID), 
	NOBLOCKS SMALLINT NOT NULL, 
	NOSLIDES SMALLINT NOT NULL, 
	NOFRAGS SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	VALUE4 DECIMAL(5,3) NOT NULL, 
	DESCR VARCHAR(64) NOT NULL)

CREATE TABLE Orders (
	SPECID INT NOT NULL REFERENCES Specimens (SPECID), 
	GRPID SMALLINT NOT NULL REFERENCES Groups (ID), 
	QTY SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL,  
	VALUE2 DECIMAL(5,3) NOT NULL,  
	VALUE3 DECIMAL(5,3) NOT NULL,  
	VALUE4 DECIMAL(5,3) NOT NULL, 
	PRIMARY KEY (SPECID, GRPID))

CREATE TABLE Comments (
	CASEID INT NOT NULL PRIMARY KEY REFERENCES Cases (CASEID), 
	COMMENT VARCHAR(32600) NOT NULL)

CREATE TABLE Frozens (
	CASEID INT NOT NULL PRIMARY KEY REFERENCES Cases (CASEID), 
	PERID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	NOSPECS SMALLINT NOT NULL, 
	NOBLOCKS SMALLINT NOT NULL, 
	NOSLIDES SMALLINT NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	VALUE4 DECIMAL(5,3) NOT NULL)

CREATE TABLE Additional (
	CASEID INT NOT NULL REFERENCES Cases (CASEID), 
	PERID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	CODEID SMALLINT NOT NULL, 
	FINALED DATE NOT NULL, 
	VALUE1 DECIMAL(5,3) NOT NULL, 
	VALUE2 DECIMAL(5,3) NOT NULL, 
	VALUE3 DECIMAL(5,3) NOT NULL, 
	VALUE4 DECIMAL(5,3) NOT NULL,  
	PRIMARY KEY (CASEID, PERID, CODEID, FINALED))

CREATE TABLE Errors (
	CASEID INT NOT NULL PRIMARY KEY,
	ERRID INT NOT NULL, 
	CASENO CHAR(12) NOT NULL, 
	COMMENT VARCHAR(8000) NOT NULL)

CREATE TABLE Pending (
	CASEID INT NOT NULL PRIMARY KEY, 
	FACID SMALLINT NOT NULL REFERENCES Facilities (FACID), 
	MSID SMALLINT NOT NULL REFERENCES MasterSpecimens (MSID), 
	GROSSTAT SMALLINT NOT NULL DEFAULT 0, 
	EMBEDTAT SMALLINT NOT NULL DEFAULT 0, 
	MICROTAT SMALLINT NOT NULL DEFAULT 0, 
	STAINTAT SMALLINT NOT NULL DEFAULT 0, 
	ROUTETAT SMALLINT NOT NULL DEFAULT 0, 
	HISTOTAT SMALLINT NOT NULL DEFAULT 0, 
	FINALTAT SMALLINT NOT NULL DEFAULT 0, 
	GROSSID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	EMBEDID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	MICROID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	STAINID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	ROUTEID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	FINALID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	SUBID SMALLINT NOT NULL REFERENCES Subspecial (SUBID), 
	PROID SMALLINT NOT NULL, 
	STATUS SMALLINT NOT NULL, 
	NOSPECS SMALLINT NOT NULL, 
	NOBLOCKS SMALLINT NOT NULL, 
	NOSLIDES SMALLINT NOT NULL, 
	ACCESSED TIMESTAMP NOT NULL, 
	GROSSED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	EMBEDED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	MICROED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	STAINED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	ROUTED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	FINALED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	CASENO CHAR(12) UNIQUE NOT NULL)

CREATE TABLE Stats (
	CASEID INT NOT NULL PRIMARY KEY, 
	FACID SMALLINT NOT NULL REFERENCES Facilities (FACID), 
	GROSSID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	FINALID SMALLINT NOT NULL REFERENCES Personnel (PERID), 
	SPYID SMALLINT NOT NULL REFERENCES Specialties (SPYID), 
	SUBID SMALLINT NOT NULL REFERENCES Subspecial (SUBID), 
	PROID SMALLINT NOT NULL, 
	NOSPECS SMALLINT NOT NULL, 
	NOBLOCKS SMALLINT NOT NULL, 
	NOSLIDES SMALLINT NOT NULL, 
	NOHE SMALLINT NOT NULL, 
	NOSS SMALLINT NOT NULL, 
	NOIHC SMALLINT NOT NULL, 
	NOMOL SMALLINT NOT NULL, 
	NOFSP SMALLINT NOT NULL, 
	NOFBL SMALLINT NOT NULL, 
	NOFSL SMALLINT NOT NULL, 
	NOSYN SMALLINT NOT NULL, 
	GRTAT SMALLINT NOT NULL, 
	ROTAT SMALLINT NOT NULL, 
	FITAT SMALLINT NOT NULL, 
	TOTAT SMALLINT NOT NULL, 
	MSID SMALLINT NOT NULL REFERENCES MasterSpecimens (MSID), 
	ACCESSED TIMESTAMP NOT NULL, 
	GROSSED TIMESTAMP NOT NULL, 
	ROUTED TIMESTAMP NOT NULL, 
	FINALED TIMESTAMP NOT NULL, 
	CASENO CHAR(12) UNIQUE NOT NULL)

CREATE INDEX Cases_Finaled ON Cases (FINALED)

CREATE INDEX Additional_Finaled ON Additional (FINALED)

CREATE INDEX Additional_Personnel ON Additional (PERID)

CREATE INDEX Stats_Finaled ON Stats (FINALED)

